---

- hosts: master
  become: yes
  tasks: 
    - name: Install pip3 with python3
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install pip Docker
      pip:
        name: 
          - docker
        state: present

    - name: Install node_exporter container
      docker_container:
        name: node_exporter
        image: quay.io/prometheus/node-exporter:latest
        command:
          - '--path.rootfs=/host'
        network_mode: host
        pid_mode: host
        volumes:
          - '/:/host:ro,rslave'
        restart: yes
        restart_policy: always